import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "@components/navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center">
        <div className="max-w-2xl w-full">
          <Navbar />
        </div>
      </div>

      <main className="flex flex-col items-center mt-2 mx-2">
        <div className="max-w-2xl">
          <h1 className="text-4xl font-bold text-center sm:text-left">
            Hey, I&apos;m <span className="text-bgreen">Juan Cortelezzi</span>
          </h1>
          <div className="py-2" />
          <p>
            I&apos;m a self taught web developer, currently studying software
            engeneering at UADE University. You&apos;ve found my personal slice
            of the internet, feel free to look around.
          </p>
          <div className="py-1" />
          <p>
            In this page you will be able to see my current projects by clicking
            on the Projects link up top, as well as taking a look at my latest
            posts/tutorials on the blog link besides the projects one
          </p>
        </div>
      </main>
    </div>
  );
};

export default Home;
